<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WowzaSample.Client\WowzaSample.Client.csproj" />
    <ProjectReference Include="..\WowzaSample.Shared\WowzaSample.Shared.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="11.0.0-preview.5.26302.115" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="11.0.0-preview.5.26302.115" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="_removed\**" />
    <Content Remove="_removed\**" />
  </ItemGroup>

</Project>
